# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: JBoss Modules CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-test-matrix:
    name: ${{ matrix.jdk-distribution }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        jdk-distribution: [temurin, adopt-openj9]
    steps:
    - name: Configure runner - Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo bash -c "echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > /etc/hosts"
        sudo bash -c "echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> /etc/hosts"
    - name: Configure Runner - Windows
      if: contains(matrix.os, 'windows')
      run: |
        echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' > %SystemRoot%\System32\drivers\etc\hosts
        echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6' >> %SystemRoot%\System32\drivers\etc\hosts
      shell: cmd
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.jdk-distribution }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ matrix.jdk-distribution }}
        java-version: |
          11
          17
          21
    - name: Run Tests
      run: mvn -ntp -U -B -fae clean install "-Djava11.home=${{env.JAVA_HOME_11_X64}}" "-Djava17.home=${{env.JAVA_HOME_17_X64}}"
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: surefire-${{ matrix.jdk-distribution }}-${{ matrix.os }}
        path: '**/surefire-reports/*.txt'
